# Generated by Django 4.0.3 on 2022-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Имя пилота')),
                ('content', models.TextField(blank=True, verbose_name='О пилоте')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото пилота')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Метка публикации')),
            ],
        ),
    ]
